#!/usr/bin/env bash

# vim:ft=sh
# File: $TSAENODE_HOME/tsaenode


version=1.0

codebase=${TSAENODE_HOME:-$PWD}/tsaenode-${version}.jar
config=${TSAENODE_HOME:-$PWD}/tsaenode.conf

rmiPort=1099


print_usage() {
  printf "Usage: tsaenode [-options]\n"
  printf "where options include:\n"
  printf "\t-h\t\tprint this help message\n"
  printf "\t-f\t\tconfig file path\n"
  printf "\t-r <port>\tset Java RMI registry port\n"
}


while getopts ":f:r:h" opt; do
  case $opt in
    (f) config="${OPTARG}" ;;
    (r) rmiPort=${OPTARG} ;;
    (h)
      print_usage
      exit 0
      ;;
    (\?)
      echo "Invalid option: -${OPTARG}" >&2
      print_usage
      exit -1
      ;;
    (:)
      echo "Option -${OPTARG} requires an argument." >&2
      print_usage
      exit -1
      ;;
  esac
done
shift $((OPTIND-1))


echo "Starting Java RMI registry at port ${rmiPort}..."
gnome-terminal  -t "Java RMI registry at port ${rmiPort}" \
                -x rmiregistry ${rmiPort}


echo "Starting TSAEnode..."
gnome-terminal  -t "TSAEnode" \
                -x java -cp ${codebase} \
                        -Djava.rmi.server.codebase=file://${codebase} \
                        -Dconfig.file=${config} \
                        -DrmiPort=${rmiPort} \
                        org.coderebels.tsaenode.Main


unset rmiPort config codebase version
exit 0
